fix(pkce): replace openid pkce generators with own implementations
opengovsg/sgid-client pull request #52
Opened 2023-05-23 07:51 UTC by kschiew

## Problem

_What problem are you trying to solve? What issue does this close?_

Closes [insert issue #]

## Solution

_How did you solve the problem?_

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

_What tests should be run to confirm functionality?_

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

2023-05-23 07:55 UTC, PrawiraGenestonlia approved these changes
lgtm! will let @mantariksh do the final check.

2023-05-24 03:39 UTC, mantariksh reviewed
hmm...it seems like we are committing to support `generatePkcePair` in browser environments. but if we are making this commitment, we should have corresponding unit tests.

currently our unit tests only use a Node environment (see `jest.config.js`). I think we should set up separate tests to test for the browser environment. there are a few ways to do this, but we can start here: https://jestjs.io/docs/configuration#testenvironment-string

wdyt?

2023-05-24 03:43 UTC, PrawiraGenestonlia requested changes
This did not pass browser test for me.

2023-05-24 03:46 UTC, PrawiraGenestonlia commented
> hmm...it seems like we are committing to support `generatePkcePair` in browser environments. but if we are making this commitment, we should have corresponding unit tests.
> 
> 
> 
> currently our unit tests only use a Node environment (see `jest.config.js`). I think we should set up separate tests to test for the browser environment. there are a few ways to do this, but we can start here: https://jestjs.io/docs/configuration#testenvironment-string
> 
> 
> 
> wdyt?

Agree. I have a follow up question. Should we go with
1. Conditional import (import xx from "@opengovsg/sgid-client/browser)
2. Import path remains the same as node js but within the client, we will need to export accordingly - see jose package.

2023-05-24 04:04 UTC, mantariksh commented
another approach is to keep this repo for NodeJS, and have a completely separate one for browsers. advantage is separation of concerns and makes the package footprint smaller for client frontends.

2023-05-24 04:21 UTC, raynerljm commented
i agree with @mantariksh - i'm more inclined towards having a separate repo intended for browsers so as not to blur the lines between Node.js and browser environments

2023-05-24 09:17 UTC, kwajiehao commented
Discussed with @kschiew offline - my take is that we shouldn't make any rash decisions on updating our offering before we figure out whether we want to support a frontend PKCE generation flow. So in the meantime, we can use a third-party library like [pkce-challenge](https://www.npmjs.com/package/pkce-challenge) for the dev portal while Wira and Kok Seng figure out what the best practice here is

2023-05-25 04:48 UTC, kschiew commented
Closing PR until a new team decision is made.

2023-05-25 04:48 UTC, closed without merging